import { AccentColor } from '../types';

export interface ColorScheme {
  primaryBg: string;
  lightBg: string;
  lightBgHover: string;
  border: string;
  borderHover: string;
  text: string;
  textHover: string;
  ring: string;
  hoverBg: string;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  gradientFrom: string;
  // Dark mode properties
  darkLightBg: string;
  darkBorder: string;
  darkText: string;
  darkBadgeBg: string;
  darkBadgeText: string;
  darkBadgeBorder: string;
  darkGradientFrom: string;
}

export const colorSchemes: Record<AccentColor, ColorScheme> = {
  emerald: {
    primaryBg: "bg-emerald-600",
    lightBg: "bg-emerald-50",
    lightBgHover: "hover:bg-emerald-100",
    border: "border-emerald-200",
    borderHover: "border-emerald-400",
    text: "text-emerald-600",
    textHover: "hover:text-emerald-700",
    ring: "focus:ring-emerald-500",
    hoverBg: "hover:bg-emerald-700",
    badgeBg: "bg-emerald-50/70",
    badgeText: "text-emerald-700",
    badgeBorder: "border-emerald-100",
    gradientFrom: "from-emerald-600",
    darkLightBg: "bg-emerald-950/40",
    darkBorder: "border-emerald-800/40",
    darkText: "text-emerald-400",
    darkBadgeBg: "bg-emerald-950/30",
    darkBadgeText: "text-emerald-300",
    darkBadgeBorder: "border-emerald-900/50",
    darkGradientFrom: "from-emerald-400",
  },
  violet: {
    primaryBg: "bg-violet-600",
    lightBg: "bg-violet-50",
    lightBgHover: "hover:bg-violet-100",
    border: "border-violet-200",
    borderHover: "border-violet-400",
    text: "text-violet-600",
    textHover: "hover:text-violet-700",
    ring: "focus:ring-violet-500",
    hoverBg: "hover:bg-violet-700",
    badgeBg: "bg-violet-50/70",
    badgeText: "text-violet-700",
    badgeBorder: "border-violet-100",
    gradientFrom: "from-violet-600",
    darkLightBg: "bg-violet-950/40",
    darkBorder: "border-violet-800/40",
    darkText: "text-violet-400",
    darkBadgeBg: "bg-violet-950/30",
    darkBadgeText: "text-violet-300",
    darkBadgeBorder: "border-violet-900/50",
    darkGradientFrom: "from-violet-400",
  },
  amber: {
    primaryBg: "bg-amber-600",
    lightBg: "bg-amber-50",
    lightBgHover: "hover:bg-amber-100",
    border: "border-amber-200",
    borderHover: "border-amber-400",
    text: "text-amber-600",
    textHover: "hover:text-amber-700",
    ring: "focus:ring-amber-500",
    hoverBg: "hover:bg-amber-700",
    badgeBg: "bg-amber-50/70",
    badgeText: "text-amber-700",
    badgeBorder: "border-amber-100",
    gradientFrom: "from-amber-600",
    darkLightBg: "bg-amber-950/40",
    darkBorder: "border-amber-800/40",
    darkText: "text-amber-400",
    darkBadgeBg: "bg-amber-950/30",
    darkBadgeText: "text-amber-300",
    darkBadgeBorder: "border-amber-900/50",
    darkGradientFrom: "from-amber-400",
  },
  sky: {
    primaryBg: "bg-sky-600",
    lightBg: "bg-sky-50",
    lightBgHover: "hover:bg-sky-100",
    border: "border-sky-200",
    borderHover: "border-sky-400",
    text: "text-sky-600",
    textHover: "hover:text-sky-700",
    ring: "focus:ring-sky-500",
    hoverBg: "hover:bg-sky-700",
    badgeBg: "bg-sky-50/70",
    badgeText: "text-sky-700",
    badgeBorder: "border-sky-100",
    gradientFrom: "from-sky-600",
    darkLightBg: "bg-sky-950/40",
    darkBorder: "border-sky-800/40",
    darkText: "text-sky-400",
    darkBadgeBg: "bg-sky-950/30",
    darkBadgeText: "text-sky-300",
    darkBadgeBorder: "border-sky-900/50",
    darkGradientFrom: "from-sky-400",
  },
  rose: {
    primaryBg: "bg-rose-600",
    lightBg: "bg-rose-50",
    lightBgHover: "hover:bg-rose-100",
    border: "border-rose-200",
    borderHover: "border-rose-400",
    text: "text-rose-600",
    textHover: "hover:text-rose-700",
    ring: "focus:ring-rose-500",
    hoverBg: "hover:bg-rose-700",
    badgeBg: "bg-rose-50/70",
    badgeText: "text-rose-700",
    badgeBorder: "border-rose-100",
    gradientFrom: "from-rose-600",
    darkLightBg: "bg-rose-950/40",
    darkBorder: "border-rose-800/40",
    darkText: "text-rose-400",
    darkBadgeBg: "bg-rose-950/30",
    darkBadgeText: "text-rose-300",
    darkBadgeBorder: "border-rose-900/50",
    darkGradientFrom: "from-rose-400",
  },
  indigo: {
    primaryBg: "bg-indigo-600",
    lightBg: "bg-indigo-50",
    lightBgHover: "hover:bg-indigo-100",
    border: "border-indigo-200",
    borderHover: "border-indigo-400",
    text: "text-indigo-600",
    textHover: "hover:text-indigo-700",
    ring: "focus:ring-indigo-500",
    hoverBg: "hover:bg-indigo-700",
    badgeBg: "bg-indigo-50/70",
    badgeText: "text-indigo-700",
    badgeBorder: "border-indigo-100",
    gradientFrom: "from-indigo-600",
    darkLightBg: "bg-indigo-950/40",
    darkBorder: "border-indigo-800/40",
    darkText: "text-indigo-400",
    darkBadgeBg: "bg-indigo-950/30",
    darkBadgeText: "text-indigo-300",
    darkBadgeBorder: "border-indigo-900/50",
    darkGradientFrom: "from-indigo-400",
  }
};
